"use client"

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Textarea } from '@/components/ui/textarea'
import {
    AlertTriangle,
    CheckCircle,
    Copy,
    Download,
    ExternalLink,
    Loader2,
    MessageSquare,
    Search,
    XCircle
} from 'lucide-react'
import { useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

interface SourceItem {
  id: number
  title: string
  url: string
  provider: string
  publishedAt?: string
  authors?: string[]
  snippet?: string
  summary?: string
  reliability?: number
  sentiment?: 'pos' | 'neu' | 'neg'
  bias?: { leaning: 'left' | 'right' | 'center' | 'unknown'; strength?: number }
}

interface DeepDiveModalProps {
  source: SourceItem
  onFollowUp?: (question: string) => void
  onCrossReference?: () => void
  onExportCitation?: (format: 'bibtex' | 'apa' | 'mla') => void
}

export function DeepDiveModal({ 
  source, 
  onFollowUp, 
  onCrossReference, 
  onExportCitation 
}: DeepDiveModalProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [deepContent, setDeepContent] = useState<string>('')
  const [followUpQuestion, setFollowUpQuestion] = useState('')
  const [crossRefResults, setCrossRefResults] = useState<unknown[]>([])

  const handleDeepDive = async () => {
    setIsLoading(true)
    try {
      // Simulate fetching full content and re-summarizing
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      const mockDeepContent = `# Deep Analysis: ${source.title}

## Extended Summary
This is a comprehensive analysis of the source material, providing deeper insights beyond the initial snippet.

### Key Findings
- **Primary Focus**: The main topic addresses...
- **Methodology**: Research approach includes...
- **Implications**: The findings suggest...

### Detailed Analysis
${source.snippet || 'Original content would be fetched and analyzed here...'}

### Context and Background
Additional context about the research domain, related work, and significance within the broader field.

### Limitations and Future Work
Discussion of study limitations and suggested areas for future investigation.

---
*This deep dive analysis was generated by processing the full source content.*`

      setDeepContent(mockDeepContent)
    } catch {
      setDeepContent('Error fetching detailed content. Please try again.')
    } finally {
      setIsLoading(false)
    }
  }

  const handleCrossReference = async () => {
    setIsLoading(true)
    try {
      // Simulate cross-referencing claims
      await new Promise(resolve => setTimeout(resolve, 1500))
      
      const mockCrossRef = [
        {
          claim: "AI models show 95% accuracy in medical diagnosis",
          status: 'verified',
          matchingSources: 3,
          confidence: 0.87
        },
        {
          claim: "Implementation costs reduced by 40%",
          status: 'disputed',
          matchingSources: 1,
          confidence: 0.34
        },
        {
          claim: "Patient satisfaction increased significantly",
          status: 'unverified',
          matchingSources: 0,
          confidence: 0.12
        }
      ]
      
      setCrossRefResults(mockCrossRef)
    } catch {
      setCrossRefResults([])
    } finally {
      setIsLoading(false)
    }
  }

  const handleFollowUpSubmit = () => {
    if (followUpQuestion.trim() && onFollowUp) {
      onFollowUp(`Regarding "${source.title}": ${followUpQuestion}`)
      setFollowUpQuestion('')
      setIsOpen(false)
    }
  }

  const copyToClipboard = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  const generateCitation = (format: 'bibtex' | 'apa' | 'mla') => {
    const authors = source.authors?.join(', ') || 'Unknown Author'
    const year = source.publishedAt ? new Date(source.publishedAt).getFullYear() : new Date().getFullYear()
    
    switch (format) {
      case 'bibtex':
        return `@article{source${source.id},
  title={${source.title}},
  author={${authors}},
  year={${year}},
  url={${source.url}},
  publisher={${source.provider}}
}`
      case 'apa':
        return `${authors} (${year}). ${source.title}. Retrieved from ${source.url}`
      case 'mla':
        return `${authors}. "${source.title}." ${source.provider}, ${year}, ${source.url}.`
      default:
        return source.url
    }
  }

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="h-8 text-xs">
          <Search className="w-3 h-3 mr-1" />
          Deep Dive
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-hidden">
        <DialogHeader>
          <DialogTitle className="text-lg font-semibold pr-8">
            Deep Analysis: {source.title}
          </DialogTitle>
        </DialogHeader>
        
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 h-[70vh]">
          {/* Main Content Area */}
          <div className="lg:col-span-2">
            <ScrollArea className="h-full pr-4">
              <div className="space-y-4">
                {/* Source Info */}
                <Card>
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-2">
                        <Badge variant="outline">{source.provider.toUpperCase()}</Badge>
                        {source.reliability && (
                          <Badge variant="outline" className={
                            source.reliability >= 0.8 ? 'border-green-500 text-green-700' :
                            source.reliability >= 0.6 ? 'border-yellow-500 text-yellow-700' :
                            'border-red-500 text-red-700'
                          }>
                            Reliability: {Math.round(source.reliability * 100)}%
                          </Badge>
                        )}
                      </div>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => window.open(source.url, '_blank')}
                      >
                        <ExternalLink className="w-4 h-4" />
                      </Button>
                    </div>
                    
                    {source.authors && (
                      <p className="text-sm text-gray-600 mb-2">
                        Authors: {source.authors.join(', ')}
                      </p>
                    )}
                    
                    {source.publishedAt && (
                      <p className="text-sm text-gray-600 mb-3">
                        Published: {new Date(source.publishedAt).toLocaleDateString()}
                      </p>
                    )}
                    
                    <div className="flex gap-2">
                      <Button
                        onClick={handleDeepDive}
                        disabled={isLoading}
                        size="sm"
                        className="flex-1"
                      >
                        {isLoading ? (
                          <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        ) : (
                          <Search className="w-4 h-4 mr-2" />
                        )}
                        {deepContent ? 'Refresh Analysis' : 'Generate Deep Analysis'}
                      </Button>
                      
                      <Button
                        onClick={handleCrossReference}
                        disabled={isLoading}
                        variant="outline"
                        size="sm"
                        className="flex-1"
                      >
                        {isLoading ? (
                          <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        ) : (
                          <CheckCircle className="w-4 h-4 mr-2" />
                        )}
                        Cross-Reference
                      </Button>
                    </div>
                  </CardContent>
                </Card>

                {/* Deep Content */}
                {deepContent && (
                  <Card>
                    <CardContent className="p-4">
                      <div className="flex items-center justify-between mb-3">
                        <h3 className="font-semibold">Deep Analysis</h3>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => copyToClipboard(deepContent)}
                        >
                          <Copy className="w-4 h-4" />
                        </Button>
                      </div>
                      <div className="prose prose-sm max-w-none">
                        <ReactMarkdown remarkPlugins={[remarkGfm]}>
                          {deepContent}
                        </ReactMarkdown>
                      </div>
                    </CardContent>
                  </Card>
                )}

                {/* Cross-Reference Results */}
                {crossRefResults.length > 0 && (
                  <Card>
                    <CardContent className="p-4">
                      <h3 className="font-semibold mb-3">Cross-Reference Results</h3>
                      <div className="space-y-3">
                        {crossRefResults.map((result, idx) => (
                          <div key={idx} className="flex items-start gap-3 p-3 border rounded">
                            <div className="flex-shrink-0 mt-1">
                              {result.status === 'verified' && <CheckCircle className="w-4 h-4 text-green-600" />}
                              {result.status === 'disputed' && <XCircle className="w-4 h-4 text-red-600" />}
                              {result.status === 'unverified' && <AlertTriangle className="w-4 h-4 text-yellow-600" />}
                            </div>
                            <div className="flex-1">
                              <p className="text-sm font-medium mb-1">{result.claim}</p>
                              <div className="flex items-center gap-2 text-xs text-gray-600">
                                <Badge variant="outline" className={`text-xs ${
                                  result.status === 'verified' ? 'border-green-500 text-green-700' :
                                  result.status === 'disputed' ? 'border-red-500 text-red-700' :
                                  'border-yellow-500 text-yellow-700'
                                }`}>
                                  {result.status.toUpperCase()}
                                </Badge>
                                <span>Sources: {result.matchingSources}</span>
                                <span>Confidence: {Math.round(result.confidence * 100)}%</span>
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                )}
              </div>
            </ScrollArea>
          </div>

          {/* Sidebar */}
          <div className="space-y-4">
            {/* Follow-up Question */}
            <Card>
              <CardContent className="p-4">
                <h3 className="font-semibold mb-3">Ask Follow-up</h3>
                <Textarea
                  placeholder="Ask a specific question about this source..."
                  value={followUpQuestion}
                  onChange={(e) => setFollowUpQuestion(e.target.value)}
                  className="mb-3"
                  rows={3}
                />
                <Button
                  onClick={handleFollowUpSubmit}
                  disabled={!followUpQuestion.trim()}
                  size="sm"
                  className="w-full"
                >
                  <MessageSquare className="w-4 h-4 mr-2" />
                  Ask Question
                </Button>
              </CardContent>
            </Card>

            {/* Citation Export */}
            <Card>
              <CardContent className="p-4">
                <h3 className="font-semibold mb-3">Export Citation</h3>
                <div className="space-y-2">
                  {(['apa', 'bibtex', 'mla'] as const).map((format) => (
                    <Button
                      key={format}
                      variant="outline"
                      size="sm"
                      className="w-full justify-start"
                      onClick={() => {
                        const citation = generateCitation(format)
                        copyToClipboard(citation)
                        if (onExportCitation) onExportCitation(format)
                      }}
                    >
                      <Download className="w-4 h-4 mr-2" />
                      {format.toUpperCase()}
                    </Button>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Source Actions */}
            <Card>
              <CardContent className="p-4">
                <h3 className="font-semibold mb-3">Actions</h3>
                <div className="space-y-2">
                  <Button
                    variant="outline"
                    size="sm"
                    className="w-full justify-start"
                    onClick={() => window.open(source.url, '_blank')}
                  >
                    <ExternalLink className="w-4 h-4 mr-2" />
                    Open Source
                  </Button>
                  
                  {onCrossReference && (
                    <Button
                      variant="outline"
                      size="sm"
                      className="w-full justify-start"
                      onClick={onCrossReference}
                    >
                      <CheckCircle className="w-4 h-4 mr-2" />
                      Cross-Reference
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
